# permissions for end users to edit billngs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: billng-editor-role
rules:
- apiGroups:
  - credentials.tmax.io
  resources:
  - billngs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - credentials.tmax.io
  resources:
  - billngs/status
  verbs:
  - get
