# permissions for end users to view cloudcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcredential-viewer-role
rules:
- apiGroups:
  - credentials.tmax.io
  resources:
  - cloudcredentials
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - credentials.tmax.io
  resources:
  - cloudcredentials/status
  verbs:
  - get
