# permissions for end users to edit cloudcredentials.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcredential-editor-role
rules:
- apiGroups:
  - credentials.tmax.io
  resources:
  - cloudcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - credentials.tmax.io
  resources:
  - cloudcredentials/status
  verbs:
  - get
