
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - credentials.tmax.io
  resources:
  - billngs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - credentials.tmax.io
  resources:
  - billngs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - credentials.tmax.io
  resources:
  - cloudcredentials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - credentials.tmax.io
  resources:
  - cloudcredentials/status
  verbs:
  - get
  - patch
  - update
