apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: hypercloud5-system
---
apiVersion: v1
kind: Secret
metadata:
  name: service-account-token
  annotations:
    kubernetes.io/service-account.name: cloud-credential-operator-service-account
type: kubernetes.io/service-account-token